# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        java-version: [ '11', '17' ]

    steps:
      - uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Check the code format
        run: |
          mvn spotless:check
      - name: Compile the main/test code
        run: |
          mvn --no-transfer-progress -DfailIfNoTests=false '-Dtest=tests.**.*Test' test
